package com.sport.service.entities.enums.place;

public enum SubDistrict {
    //ZHELEZNODOROZHNYY
    PROCESSOR,
    FROM_OSTUZHEVO_RING_TO_CHERNAVSKAAY_DAM,
    ELECTRONIKA,
    FROM_OSTUZHEVO_RING_TO_RAILWAY_BRIDGE,
    OTROZHKA_BOROVOE_SOMOVO,

    //LEVOBEREZHNYY
    VAI_KRASNYY_OKTYABR,
    DIMITROVA_STREET,
    FROM_CHERNAVSKYY_BRIDGE_TO_VOGRESOVSKYY_BRIDGE,
    PESCHANKA_OZERKI_SHINNIK_1_STARYY_MASHMET_BAM_MASHMET,

    //LENINSKYY---

    //SOVETSKYY
    SHILOVO,
    PRIDONSKOYY_PODKLETNOE,
    PERVOE_MAAY_UGO_ZAPADNYY_ZAPADNYY_POSELOK,
    TENNISTYY_ZAYYMISHE,
    FROM_NOVYY_BOMBEY_TO_ARMADA_TO_DEPUTATKA,

    //CENTRALNYY
    FROM_VGU_TO_SEVERNYY_BRIDGE,
    REST_OF_CENTRALNYY_DISTRICT,

    //KOMINTERNOVSKYY
    PODGORNOE_HVOINYY_ZADONIE,
    SEVERNYY,
    FROM_45_DIVISII_STREET_TO_9_YANVARY_STREET_AND_TO_MP,
    IPPODROM_FROM_MP_TO_ROTONDA_TO_URITSKOGO_STREET,

    ALL_SUBDISTRICTS
}