package com.sport.service.entities.enums.place;

public enum Subdistrict {
    //ZHELEZNODOROZHNYY
    PROCESSOR,
    FROM_OSTUZHEVO_RING_TO_CHERNAVSKAAY_DAM,
    ELECTRONIKA,
    FROM_OSTUZHEVO_RING_TO_RAILWAY_BRIDGE,
    OTROZHKA,

    //LEVOBEREZHNYY
    VAI_AND_QUARTER_KRASNYY_OKTYABR,
    DIMITROVA_STREET,
    FROM_CHERNAVSKYY_BRIDGE_TO_VOGRESOVSKYY_BRIDGE,
    STARYY_MASHMET,
    BAM,
    PESCHANKA_AND_OZERKI_AND_SHINNIK_1,

    //LENINSKYY---

    //SOVETSKYY
    SHILOVO,
    PRIDONSKOYY_AND_PODKLETNOE,
    PERVOE_MAAY_AND_UGO_ZAPADNYY_AND_ZAPADNYY_POSELOK,
    TENNISTYY_AND_ZAYYMISHE,
    FROM_NOVYY_BOMBEY_TO_ARMADA_TO_DEPUTATKA,

    //CENTRALNYY
    FROM_VGU_TO_SEVERNYY_BRIDGE,
    REST_OF_CENTRALNYY_DISTRICT,

    //KOMINTERNOVSKYY
    PODGORNOE,
    SEVERNYY,
    FROM_45_DIVISII_STREET_TO_9_YANVARY_STREET_AND_TO_MP,
    QUARTER_IPPODROM_AND_FROM_MP_TO_ROTONDA_AND_TO_URITSKOGO_STREET,

    ALL_SUBDISTRICTS
}