name: sportguide
services:

  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  redis:
    image: redis:7.0.12
    container_name: redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 20
    command: redis-server --replicaof no one --maxmemory 512mb --maxmemory-policy allkeys-lru --appendonly yes
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "6379:6379"

  app:
    restart: on-failure
    ports:
      - "8081:8081"
    build: .
    volumes:
      - ./logs:/app/logs
    container_name: app
    depends_on:
#      keycloak:
#        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?currentSchema=app_schema
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: [ "sh", "-c", "java -jar /app/app.jar" ]

#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#      args:
#        VITE_API_BASE_URL: http://api.sportguide.online
#    ports:
#      - "3001:80"
#    depends_on:
#      - app
#    restart: on-failure

#  grafana:
#    container_name: grafana
#    env_file:
#      - .env
#    build: ./config/grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./config/grafana/provisioning:/etc/grafana/provisioning
#    environment:
#      - GF_SERVER_ROOT_URL=https://grafana.sportguide.online
#      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
#      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
#      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_CLIENT_ID}
#      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${KEYCLOAK_SECRET}
#      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
#      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.sportguide.online/realms/sportguide/protocol/openid-connect/auth
#      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.sportguide.online/realms/sportguide/protocol/openid-connect/token
#      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.sportguide.online/realms/sportguide/protocol/openid-connect/userinfo
#      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://auth.sportguide.online/realms/sportguide/protocol/openid-connect/logout
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
#    depends_on:
#      - prometheus

#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./config/prometheus/alerts.yml:/etc/prometheus/alerts.yml
#      - ./prometheus:/prometheus

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    environment:
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN=${KEYCLOAK_MAIN_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_MAIN_ADMIN_PASSWORD}
      - KC_HEALTH_ENABLED=true
    command: start-dev --import-realm
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'exec 3<>/dev/tcp/localhost/9000 && printf \"GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && cat <&3 | grep \"200\"'",
        ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    ports:
      - "8080:8080"
#  keycloak:
#    image: quay.io/keycloak/keycloak:25.0.1
#    container_name: keycloak
#    environment:
#      - KEYCLOAK_ADMIN=${KEYCLOAK_MAIN_ADMIN}
#      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_MAIN_ADMIN_PASSWORD}
#      - KC_HEALTH_ENABLED=true
#      - KC_PROXY=edge
#      - KC_HOSTNAME=auth.sportguide.online
#      - KC_HOSTNAME_ADMIN_URL=http://keycloak:8080
#      - KC_HTTP_ENABLED=true
#      - KC_HOSTNAME_STRICT=false
#      - KC_HOSTNAME_STRICT_HTTPS=false
#    command: start-dev --import-realm
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 60
#      start_period: 60s
#    volumes:
#      - ./keycloak/realm-export:/opt/keycloak/data/import
#    ports:
#      - "8080:8080"

#  alertmanager:
#    container_name: alertmanager
#    image: prom/alertmanager:latest
#    ports:
#      - "9093:9093"
#    volumes:
#      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml