telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_NAME}
  mainAdminId: ${MAIN_ADMIN_ID}

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN

spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=app_schema&reWriteBatchedInserts=true&stringtype=unspecified
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 600000
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app_schema
        hbm2ddl:
          create_namespaces: true
        jdbc:
          lob:
            non_contextual_creation: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  sql:
    init:
      mode: never
      schema-locations: classpath:init.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
  main:
    web-application-type: none

app:
  redis:
    enable: true
    data-loader:
      enabled: true