telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_NAME}
  mainAdminId: ${MAIN_ADMIN_ID}
  secondAdminId: ${SECOND_ADMIN_ID}

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8081

spring:
  cloud:
    openfeign:
      oauth2:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/sportguide
            user-name-attribute: preferred_username
      resource-server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sportguide
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=app_schema&reWriteBatchedInserts=true&stringtype=unspecified
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 600000
#      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate.default_schema: app_schema
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app_schema
        hbm2ddl:
          create_namespaces: true
        jdbc:
          lob:
            non_contextual_creation: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  sql:
    init:
      mode: never
      schema-locations: classpath:init.sql
  h2:
    console:
      enabled: false
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus,metrics,loggers,metricsofusers
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      jvm: true
      tomcat: true
      logback: true
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    db:
      enabled: true

app:
  redis:
    enable: true
    data-loader:
      enabled: true

      #            issuer-uri: http://keycloak:8080/realms/sportguide
      #            authorization-uri: http://keycloak:8080/realms/sportguide/protocol/openid-connect/auth
      #            token-uri: http://keycloak:8080/realms/sportguide/protocol/openid-connect/token
      #            user-info-uri: http://keycloak:8080/realms/sportguide/protocol/openid-connect/userinfo
      #            jwk-set-uri: http://keycloak:8080/realms/sportguide/protocol/openid-connect/certs